canvasWidth = 650
canvasHeight = 400
baseFolderTail = "tkslidespeaker"
canvasPadX = 15
notesFontSize = 12
notesHeight = 15
notesWidth = 50
notesWrapLength = 400
notesPadX = 100
fillerFontSize = 3
copyrightText = "(C) ConnectedWorld Technology Solutions    |    http://connectedworldtech.com"
copyrightFgColor = "blue"
copyrightPadY = 5
outerButtonBgColor = "#004d00"
innerButtonBgColor = "green"
errorButtonBgColor = "darkred"
textHightlightColor = "OliveDrab1"

baseFolder = None
rootFolder = None
rootWin = None
txtPresoName = None
pageNum = 1
presentation = {"pages" : []}
can = None
can_image_container = None
txtNotes = None
goToPageCombo = None