canvasWidth = 650
canvasHeight = 400
canvasPadX = 15
notesFontSize = 10
pageNumFontSize = 10
notesHeight = 12
notesWidth = 74
notesWrapLength = 500
notesPadX = 65
fillerFontSize = 3
modalHeight = 150
modalWidth = 500
modalFontSize = 10
copyrightText = "(C) ConnectedWorld Technology Solutions    |    http://connectedworldtech.com"
copyrightFgColor = "blue"
copyrightPadY = 5
outerButtonBgColor = "#004d00"
innerButtonBgColor = "green"
errorButtonBgColor = "red"
textHightlightColor = "OliveDrab1"
autoAdvanceDelay = 3    #3 second delay before advancing to next page
isPlaying = False

home = None
appName = "tkslidespeaker"
friendlyAppName = "SlideSpeaker"
appFolder = None
stagingFolder = None
tmpFolder = None
outputFolder = None
txtPresoName = None
pageNum = 1
presentation = {"pages" : []}
autoAdvance = 0
speakerList = ["Joanna", "Amy", "Kajal", "Stephen", "Brian"]

#widgets
rootWin = None
can = None
can_image_container = None
txtNotes = None
lblPageNum = None
goToPageCombo = None
firstButton = None
lastButton = None
nextButton = None
previousButton = None
